name: deploy to gh pages

on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: check repo
        uses: actions/checkout@v2

      - name: node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: dependencies
        run: npm install

      - name: build
        run: npm run build

      - name: deploy
        run: npm run deploy
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
